# Generated by Django 2.1.1 on 2018-09-03 03:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('format', models.CharField(choices=[('LEGACY', 'Legacy'), ('VINTAGE', 'Vintage'), ('MODERN', 'Modern'), ('STANDARD', 'Standard'), ('PAUPER', 'Pauper')], max_length=50)),
                ('maindeck', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sideboard', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Archetype')),
                ('included_cards', models.ManyToManyField(to='cards.Card')),
            ],
        ),
    ]
