# Generated by Django 2.1.1 on 2018-09-03 03:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180903_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='maindeck',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='sideboard',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
